# Default values for Neo4j.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: "neo4j"

# Specs for the solution container.  See 'causal-cluster' directory.
image: "neo4j:3.5.2"
# Version for the solution container
imageTag: "3.5.2"
# Neo4j version the solution container is based on.
neo4jVersion: "3.5.2"
imagePullPolicy: "Always"
# imagePullSecret: registry-secret
acceptLicenseAgreement: "yes"
podDisruptionBudget: {}
  # minAvailable: 2
  # maxUnavailable: 1

# Use password authentication
authEnabled: true

## Specify password for neo4j user
## Defaults to a random 10-character alphanumeric string if not set and authEnabled is true
# neo4jPassword:

# Uncomment this and set it if you want to pair an existing secret service key
# maintenanceServiceKeySecret: "restore-service-key"

######################
#### CORE SERVERS  ###
######################
coreServers: 3
coreSidecarContainers: []

coreInitContainers: []
volumeMountPath: /data
volumeAnnotations: {}

## Subdirectory of core server data Persistent Volume to mount
## Useful if the volume's root directory is not empty
##
# coreVolumeSubPath: ""
volumeSize: 10Gi

## core server data Persistent Volume Storage Class
## If defined, storageClassName: <storageClass>
## If set to "-", storageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
volumeStorageClass: standard

# Pass extra vars if needed to neo4j docker containers
# coreExtraVars:
# - name: EXTRA_VAR_1
#   value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2

######################
#### READ REPLICAS ###
######################
readReplicaServers: 0

# readReplicaExtraVars:
# - name: EXTRA_VAR_1
#   value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2

# See above for examples on how to restore recent backups to read replicas.
# You need to configure this separately from core member init containers, to permit
# different configuration to apply to each node set.
readReplicaInitContainers: []

cpuRequest: 200m
cpuLimit: 8
memoryRequest: 512M
memoryLimit: 512Gi

ports:
  http: 7474
  https: 7473
  bolt: 7687
  backup: 6362
